# go build breaks in GitHub Actions when docker mounts volumes.

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.13
    command: etcd --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://etcd:2379 --data-dir /etcd-data
    ports:
      - "2379:2379"
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
