name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Start containers
      run: docker-compose -f docker-compose-github.yml up -d

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Stop containers
      if: always()
      run: docker-compose -f docker-compose-github.yml down
